apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jdw
  namespace: argocd
spec:
  description: Project for managing jdw Helm chart deployments
  sourceRepos:
    - https://github.com/jdwillmsen/jdw-apps.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: true
