revisionHistoryLimit: 1
image:
  tag: "0.2.1"

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: servicediscovery.prd.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.prd.jdwkube.com
      secretName: servicediscovery-prd-tls

serviceDiscovery:
  remotes:
    authui: https://authui.prd.jdwkube.com
    usersui: https://usersui.prd.jdwkube.com
  microFrontends:
    - name: authui
      path: auth
      remoteName: authui
      moduleName: ./Routes
      url: https://authui.prd.jdwkube.com
      icon: login
      title: Auth
      description: This contains sign in and sign up functionality
    - name: usersui
      path: users
      remoteName: usersui
      moduleName: ./Routes
      url: https://usersui.prd.jdwkube.com
      icon: groups
      title: Users
      description: This contains viewing users and managing profiles functionality