revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: servicediscovery.uat.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.uat.jdwkube.com
      secretName: servicediscovery-uat-tls

serviceDiscovery:
  config:
    authui: https://authui.uat.jdwkube.com
    usersui: https://usersui.uat.jdwkube.com