revisionHistoryLimit: 1
image:
  tag: "0.1.3"

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: servicediscovery.prd.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.prd.jdwkube.com
      secretName: servicediscovery-prd-tls

serviceDiscovery:
  config:
    authui: https://authui.prd.jdwkube.com
    usersui: https://usersui.prd.jdwkube.com