replicaCount: 1
revisionHistoryLimit: 10

image:
  repository: jdwillmsen/jdw-servicediscovery
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ss-clusterissuer
  hosts:
    - host: servicediscovery.default.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.default.jdw.com
      secretName: servicediscovery-default-tls

resources:
  requests:
    memory: "32Mi"
    cpu: "10m"
  limits:
    memory: "64Mi"
    cpu: "50m"

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes:
  - name: config-volume
    configMap:
      name: service-discovery-config

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

externalSecrets: []

envs:
  SD_PORT: 8080

envSecrets: []

serviceDiscovery:
  config:
    authui: http://authui