revisionHistoryLimit: 1

ingress:
  hosts:
    - host: servicediscovery.dev.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.dev.jdw.com
      secretName: servicediscovery-dev-tls

serviceDiscovery:
  config:
    authui: https://authui.dev.jdw.com