revisionHistoryLimit: 1

ingress:
  hosts:
    - host: servicediscovery.prd.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.prd.jdw.com
      secretName: servicediscovery-prd-tls
