revisionHistoryLimit: 1

ingress:
  hosts:
    - host: servicediscovery.uat.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.uat.jdw.com
      secretName: servicediscovery-uat-tls

serviceDiscovery:
  config:
    authui: https://authui.uat.jdw.com