image:
  tag: ""

revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: rolesui.uat.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - rolesui.uat.jdwkube.com
      secretName: rolesui-uat-tls

envs:
  ENVIRONMENT: uat
  AUTH_BASE_URL: https://usersrole.uat.jdwkube.com