replicaCount: 3

ingress:
  hosts:
    - host: container.prd.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - container.prd.jdw.com
      secretName: container-prd-tls

envs:
  ENVIRONMENT: prod