replicaCount: 3

ingress:
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: container.prd.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - container.prd.jdw.com
      secretName: { { $fullName } }-tls

envs:
  ENVIRONMENT: prod