image:
  tag: "0.4.2"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  hosts:
    - host: container.prd.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - container.prd.jdw.com
      secretName: container-prd-tls

envs:
  ENVIRONMENT: prod
  AUTH_BASE_URL: https://usersrole.prd.jdw.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.prd.jdw.com