revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: container.uat.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - container.uat.jdwkube.com
      secretName: container-uat-tls

envs:
  ENVIRONMENT: uat
  AUTH_BASE_URL: https://usersrole.uat.jdwkube.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.uat.jdwkube.com