revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: container.dev.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - container.dev.jdwkube.com
      secretName: container-dev-tls

envs:
  ENVIRONMENT: dev
  AUTH_BASE_URL: https://usersrole.dev.jdwkube.com
  SERVICE_DISCOVERY_BASE_URL: https://servicediscovery.dev.jdwkube.com