replicaCount: 1

ingress:
  hosts:
    - host: container.dev.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - container.dev.jdw.com
      secretName: container-dev-tls

envs:
  ENVIRONMENT: dev