replicaCount: 1

ingress:
  hosts:
    - host: usersrole.dev.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersrole.dev.jdw.com
      secretName: usersrole-dev-tls

envs:
  UR_PG_DATASOURCE_URL: jdbc:postgresql://postgresql-cluster-non-rw:5432/jdw