replicaCount: 1
revisionHistoryLimit: 1

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"
    cpu: "1"

ingress:
  hosts:
    - host: usersrole.dev.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersrole.dev.jdw.com
      secretName: usersrole-dev-tls

envs:
  UR_PG_DATASOURCE_URL: jdbc:postgresql://postgresql-cluster-non-rw.database:5432/jdw_dev
  UR_JWT_EXPIRATION_TIME_MS: "7200000"
  JAVA_OPTS: "-XX:+UseContainerSupport -Xms512m -Xmx1g"

envSecrets:
  - secretKey: UR_PG_USERNAME
    key: postgresql-cluster-non-app
    property: username
    secretName: postgresql-cluster-non-app
  - secretKey: UR_PG_PASSWORD
    key: postgresql-cluster-non-app
    property: password
    secretName: postgresql-cluster-non-app
  - secretKey: UR_JWT_SECRET_KEY
    key: usersrole
    property: jwt_key_dev
    secretName: usersrole