replicaCount: 3

ingress:
  hosts:
    - host: usersrole.prd.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersrole.prd.jdw.com
      secretName: usersrole-prd-tls

envs:
  UR_PG_DATASOURCE_URL: jdbc:postgresql://postgresql-cluster-prd-rw:5432/jdw