replicaCount: 1
revisionHistoryLimit: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

ingress:
  hosts:
    - host: usersrole.dev.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersrole.dev.jdw.com
      secretName: usersrole-dev-tls

externalSecrets:
  - refreshInterval: 1m
    secretStoreName: k8s-secret-store
    secretName: usersrole-pg-dev
  - refreshInterval: 1m
    secretStoreName: vault-secret-store
    secretName: usersrole-dev

envs:
  UR_PG_DATASOURCE_URL: jdbc:postgresql://postgresql-cluster-non-rw.database:5432/jdw_dev
  UR_JWT_EXPIRATION_TIME_MS: "7200000"
  JAVA_OPTS: "-Xss256K -Xmx64M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M"

envSecrets:
  - secretKey: UR_PG_USERNAME
    key: postgresql-cluster-non-app
    property: username
    secretName: usersrole-pg-dev
  - secretKey: UR_PG_PASSWORD
    key: postgresql-cluster-non-app
    property: password
    secretName: usersrole-pg-dev
  - secretKey: UR_JWT_SECRET_KEY
    key: usersrole
    property: jwt_key_dev
    secretName: usersrole-dev
