replicaCount: 1

image:
  repository: jdwillmsen/jdw-usersrole
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ss-clusterissuer
  hosts:
    - host: usersrole.default.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersrole.default.jdw.com
      secretName: usersrole-default-tls

resources: {}

livenessProbe:
  httpGet:
    path: /actuator/health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/healthoc
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

externalSecrets:
  - refreshInterval: 1m
    secretStoreName: k8s-secret-store
    secretName: postgresql-cluster-non-app
    envs:
      username: UR_PG_USERNAME
      password: UR_PG_PASSWORD

envs:
  UR_PG_DATASOURCE_URL: jdbc:postgresql://postgresql-cluster-non-rw:5432/jdw

envSecrets:
  UR_PG_USERNAME: postgresql-cluster-non-app
  UR_PG_PASSWORD: postgresql-cluster-non-app
