kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  VERSION: {{ .Chart.AppVersion | quote }}
  DATA: {{ .Values.configmap.data.DATA | quote }}