revisionHistoryLimit: 1

ingress:
  hosts:
    - host: authui.dev.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - authui.dev.jdwkube.com
      secretName: authui-dev-tls

envs:
  ENVIRONMENT: dev
  AUTH_BASE_URL: https://usersrole.dev.jdwkube.com