revisionHistoryLimit: 1

ingress:
  hosts:
    - host: authui.uat.jdw.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - authui.uat.jdw.com
      secretName: authui-uat-tls

envs:
  ENVIRONMENT: uat
  AUTH_BASE_URL: https://usersrole.uat.jdw.com