{{- range .Values.externalSecrets }}
{{- $secretName := .secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "usersrole.fullname" $ | printf "%s-%s" .secretName }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreName }}
    kind: SecretStore
  target:
    name: {{ $secretName }}
  data:
    {{- range $key, $value := .envs }}
    - secretKey: {{ $value }}
      remoteRef:
        key: {{ $secretName }}
        property: {{ $key }}
    {{- end }}
{{- end }}