replicaCount: 1

image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: ""

# This is the command busybox will run when the container starts
command:
  - "/bin/sh"
  - "-c"
  - |
    echo "Secrets:"
    echo "key1: ${key1}"
    echo "key2: ${key2}"
    echo "key3: ${key3}"
    sleep 1m

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 200
  supplementalGroups:
    - 200

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
     drop:
     - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 200

service:
  enabled: false
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
     cpu: 500m
     memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  enabled: false
  httpGet:
    path: /
    port: http
readinessProbe:
  enabled: false
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

externalSecrets:
  refreshInterval: 1m
  secretStoreName: k8s-secret-store
  secretName: test

envs: {}

envSecrets:
  key1: test
  key2: test
  key3: test
