apps:
  - appName: secret-store-dev
    helmPath: helm/secret-store
    namespace: external-secrets
    values:
      - values.yaml
  - appName: container-dev
    helmPath: helm/container
    namespace: dev
    values:
      - values-dev.yaml
  - appName: usersrole-dev
    helmPath: helm/usersrole
    namespace: dev
    values:
      - values-dev.yaml
  - appName: secrets-tester-k8s
    helmPath: helm/secrets-tester
    namespace: default
    values:
      - values-k8s.yaml
  - appName: secrets-tester-vault
    helmPath: helm/secrets-tester
    namespace: default
    values:
      - values-vault.yaml