apps:
  - appName: secret-store-dev
    helmPath: helm/secret-store
    namespace: dev
    values:
      - values-dev.yaml
  - appName: container-dev
    helmPath: helm/container
    namespace: dev
    values:
      - values-dev.yaml
  - appName: usersrole-dev
    helmPath: helm/usersrole
    namespace: dev
    values:
      - values-dev.yaml
  - appName: authui-dev
    helmPath: helm/authui
    namespace: dev
    values:
      - values-dev.yaml
  - appName: servicediscovery-dev
    helmPath: helm/servicediscovery
    namespace: dev
    values:
      - values-dev.yaml
  - appName: usersui-dev
    helmPath: helm/usersui
    namespace: dev
    values:
      - values-dev.yaml