apps:
  - appName: secret-store-dev
    helmPath: charts/secret-store
    namespace: dev
    values:
      - values-dev.yaml
  - appName: container-dev
    helmPath: charts/container
    namespace: dev
    values:
      - values-dev.yaml
  - appName: usersrole-dev
    helmPath: charts/usersrole
    namespace: dev
    values:
      - values-dev.yaml
  - appName: authui-dev
    helmPath: charts/authui
    namespace: dev
    values:
      - values-dev.yaml
  - appName: servicediscovery-dev
    helmPath: charts/servicediscovery
    namespace: dev
    values:
      - values-dev.yaml
  - appName: usersui-dev
    helmPath: charts/usersui
    namespace: dev
    values:
      - values-dev.yaml
  - appName: rolesui-dev
    helmPath: charts/rolesui
    namespace: dev
    values:
      - values-dev.yaml
