revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: usersui.dev.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersui.dev.jdwkube.com
      secretName: usersui-dev-tls

envs:
  ENVIRONMENT: dev
  AUTH_BASE_URL: https://usersrole.dev.jdwkube.com
