{{- range .Values.externalSecrets }}
{{- $secretName := .secretName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreName }}
    kind: SecretStore
  target:
    name: {{ $secretName }}
  data:
    {{- range $.Values.envSecrets }}
    {{ if eq .secretName $secretName }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .key }}
        property: {{ .property }}
    {{- end }}
    {{- end }}
---
{{- end }}