apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "secret-store.serviceAccountName" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test2
data:
  key1: amFrZQo=
  key2: ZGF2aWQ=
  key3: d2lsbG1zZW4=
  key4: dW5pdA==
  key5: dGVzdA==