apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-secret-store
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "secret-store.serviceAccountName" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: test2
data:
  key1: cf9vdasd31A==
  key2: cm9vdSDFGAadf==
  key3: cm9vdAdsac41c==