apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: external-secrets
  name: my-store
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-store.serviceAccountName" . }}
    namespace: external-secrets