revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: usersui.uat.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - usersui.uat.jdwkube.com
      secretName: usersui-uat-tls

envs:
  ENVIRONMENT: uat
  AUTH_BASE_URL: https://usersrole.uat.jdwkube.com