revisionHistoryLimit: 1

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: servicediscovery.dev.jdwkube.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - servicediscovery.dev.jdwkube.com
      secretName: servicediscovery-dev-tls

serviceDiscovery:
  remotes:
    authui: https://authui.dev.jdwkube.com
    usersui: https://usersui.dev.jdwkube.com
    rolesui: https://rolesui.dev.jdwkube.com
  microFrontends:
    - name: authui
      path: auth
      remoteName: authui
      moduleName: ./Routes
      url: https://authui.dev.jdwkube.com
      icon: login
      title: Auth
      description: This contains sign in and sign up functionality
    - name: usersui
      path: users
      remoteName: usersui
      moduleName: ./Routes
      url: https://usersui.dev.jdwkube.com
      icon: groups
      title: Users
      description: This contains viewing users and managing profiles functionality
    - name: rolesui
      path: roles
      remoteName: rolesui
      moduleName: ./Routes
      url: https://rolesui.dev.jdwkube.com
      icon: lock
      title: Roles
      description: This contains viewing and managing roles functionality