apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "secrets-tester.fullname" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.secretName }}
  data:
    {{- range $key, $value := .Values.externalSecrets.envs }}
    - secretKey: {{ $value }}
      remoteRef:
        key: {{ .Values.externalSecrets.secretStoreName }}
        property: {{ $key }}
    {{- end }}