{{- if eq .Values.type "vault" }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ include "secrets-tester.fullname" . }} # Customisable
  namespace: dev # Same of the SecretStores
spec:
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: {{ .Values.type }}-secret-store
      kind: SecretStore
  selector:
    secret:
      name: test # Source Kubernetes secret to be pushed
  data:
    - match:
        remoteRef:
          remoteKey: jake # Remote reference (where the secret is going to be pushed)
{{- end }}